---
resources:
  - name: scw-repo
    type: git
    source:
      uri: https://github.com/jacopen/springboot-concourse-workshop
      branch: develop

jobs:
  - name: unit-test
    plan:
      - get: scw-repo
        trigger: true
      - task: unit
        file: scw-repo/ci/tasks/unit.yml

